
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Muhammad Zeeshan Nawaz  ## put your name
title: 'Computer Scientist'  ## your title
location: Galway, Ireland


## Social Profiles
facebook: https://www.facebook.com/xeeshan.nawax  ## your facebook account url
twitter: https://twitter.com/imxesh  ## your twitter account url
linkedin: https://www.linkedin.com/in/muhammadzeeshannawaz/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
